# ZSH RC file

####################
# Oh My ZSH Config #
####################

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set Theme
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="af-magic"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(tmux python git)

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

###############
# User Config #
###############

export DOTFILES=$HOME/.dotfiles

# Environment Variables
source $DOTFILES/zsh/env.sh

# Aliases
source $DOTFILES/zsh/alia.sh

# Functions
source $DOTFILES/zsh/func.sh
